apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lwweb1
  name: lwweb1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lwweb1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lwweb1
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
