apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lwweb
  name: lwweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lwweb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lwweb
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
